AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cf-sam-video-transcription-translate
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Parameters:
  VideoBucketName:
    Type: String
  AudioBucketName:
    Type: String
  TranscriptionBucketName:
    Type: String
  TranslationBucketName:
    Type: String

Resources:
  VideoBucket:
    !Include ./resources/bucket/video.yaml
  AudioBucket:
    !Include ./resources/bucket/audio.yaml
  TranscriptionBucket:
    !Include ./resources/bucket/transcription.yaml
  TranslationBucket:
    !Include ./resources/bucket/translation.yaml
  ConvertVideoToAudioLambda:
    !Include ./resources/lambda/convertVideoToAudioLambda.yaml
  ConvertVideoToAudioLambdaRole:
    !Include ./resources/lambda/convertVideoToAudioLambdaRole.yaml
  MediaConvertDefaultRole:
    !Include ./resources/mediaconvert/mediaConvertDefaultRole.yaml
  TranscribeAudioLambda:
    !Include ./resources/lambda/transcribeAudioLambda.yaml
  TranscribeAudioLambdaRole:
    !Include ./resources/lambda/transcribeAudioLambdaRole.yaml
  TranslateTranscriptionLambda:
    !Include ./resources/lambda/translateTranscriptionLambda.yaml
  TranslateTranscriptionLambdaRole:
    !Include ./resources/lambda/translateTranscriptionLambdaRole.yaml

Outputs:
  ConvertVideoToAudioLambda:
    Value: !GetAtt ConvertVideoToAudioLambda.Arn
  ConvertVideoToAudioLambdaRole:
    Value: !GetAtt ConvertVideoToAudioLambdaRole.Arn