AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cf-sam-video-transcription-translate
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Parameters:
  VideoBucketName:
    Type: String
  AudioBucketName:
    Type: String
  SubtitleBucketName:
    Type: String

Resources:
  VideoBucket:
    !Include ./resources/bucket/video.yaml
  AudioBucket:
    !Include ./resources/bucket/audio.yaml
  SubtitleBucket:
    !Include ./resources/bucket/subtitle.yaml
  ConvertVideoToAudioLambda:
    !Include ./resources/lambda/convertVideoToAudioLambda.yaml
  ConvertVideoToAudioLambdaRole:
    !Include ./resources/lambda/convertVideoToAudioLambdaRole.yaml

Outputs:
  ConvertVideoToAudioLambda:
    Value: !GetAtt ConvertVideoToAudioLambda.Arn
  ConvertVideoToAudioLambdaIamRole:
    Value: !GetAtt ConvertVideoToAudioLambdaRole.Arn