    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName:
            Fn::Sub: ${AWS::StackName}-MediaConvertPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${VideoBucketName}/*"
              - Effect: Allow
                Action:
                  - "s3:Put*"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${AudioBucketName}/*"