    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: golambda/api/
      Handler: api
      Runtime: go1.x
      Architectures:
        - x86_64
      Role: !GetAtt ConvertVideoToAudioLambdaRole.Arn
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        !Include ./convertVideoToAudioLambdaEvents.yaml